fix(grafana): wrong render plugin arch
logger=grafana-apiserver t=2025-02-10T00:00:44.696800608Z level=info msg="Adding GroupVersion featuretoggle.grafana.app v0alpha1 to ResourceManager"
Error: ✗ *rendering.RenderingService run error: Unrecognized remote plugin message:
Failed to read any lines from plugin's stdout
This usually means
  the plugin was not compiled for this architecture,
  the plugin is missing dynamic-link libraries necessary to run,
  the plugin is not executable by this process due to file permissions, or
  the plugin failed to negotiate the initial go-plugin protocol handshake

Additional notes about plugin:
  Path: /var/lib/grafana/plugins/grafana-image-render/plugin_start_linux_amd64
  Mode: -rwxr-xr-x
  Owner: 472 [grafana] (current: 472 [grafana])
  Group: 472 [?] (current: 472 [?])
  ELF architecture: EM_X86_64 (current architecture: amd64)